# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile code
      run: mvn compile
     
  build:   
    runs-on: ubuntu-latest
    name: Run mvn build and generate coverage report
    steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
          java-version: 1.8
     - name: Build with Maven
       run: mvn -B package --file pom.xml -Dmaven.test.skip=true
     - name: generate report codecov
       run: mvn cobertura:cobertura
     - name: Upload coverage
       if: success()
       run: |
          curl -s https://codecov.io/bash | bash
       env:
          CODECOV_TOKEN: ${{ secrets.EZYBIZ_TOKEN }}
       shell: bash
